version: "3.9"
services:
  mongo_db:
    container_name: yolo_db
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - mongo_db:/data/db

#our backend service

  backend:
    container_name: yolo_backend
    build: ./backend
    image: cynthiawairimu/yolo_backend_img:v.1
    ports:
      - 5000:5000
    volumes:
      - .:/data
    environment:
        PORT: 5000
        MONGODB_URI: mongodb://mongo_db:27017
        DB_NAME: yolomy

    depends_on:
      - mongo_db

  # our client service
  client:
    container_name: yolo_client
    build: ./client
    image: cynthiawairimu/yolo_client_img:v.1
    tty: true
    ports:
      - 3000:3000
    environment:
        PORT: 3000
    depends_on:
      - backend
    

volumes:
  mongo_db: {}